### ISSUE TITLE
Eliminar ficheros que no correspondan a la tesis

### ISSUE THREAD

**Issue by JJ** [fergunet/tesis#1]
Por ejemplo, ¿tesis.tex del dir principal? Tiene un montón de definiciones que son de otra tesis, ¿no?

**Comment by fergunet** [comment]
Sí, es que la estoy usando de base para utilizar todas las cosas específicas de esa plantilla (tablas, figuras, definiciones...). Ya que más o menos controlo todo los voy a quitar.

**Comment by JJ** [comment]
Me acabo de corregir un fichero intro.tex que no tiene nada que ver con tu tesis. ¿Por qué no eliminas los que no lo son lo que se dice ya?

**Comment by fergunet** [comment]
Eliminados (y perdón por eso :( ).
