### ISSUE TITLE
! No room for a new \dimen .

### ISSUE THREAD

**Issue by Amab** [fergunet/tesis#10]
Al compilar la tesis aparece el error "! No room for a new \dimen ." y no se genera el fichero de salida.

Sistema Operativo: Linux Mint 16
Distribución LaTeX: texlive-full (extensiones de LaTeX incluidas)
Pygments instalado con el script easy_install que se describe en las instrucciones del enlace que hay en el fichero README.md

Traza completa de la ejecución del script "compilar": https://gist.github.com/Amab/d21fdf4638a0a5d9b132

Más información sobre el error: http://www.tex.ac.uk/cgi-bin/texfaq2html?label=noroom

**Comment by JoseTomasTocino** [comment]
A mí me da el mismo error, según [este enlace](http://tex.stackexchange.com/a/38609) parece ser por exceso de paquetes. Añadiendo esta línea se arregla (En Linux Mint 16)

```
\usepackage{etex}
```

**Comment by Amab** [comment]
Confirmo que el fix funciona.

Muchas gracias, José.
