### ISSUE TITLE
Dame argo der 1.3, aay

### ISSUE THREAD

**Issue by alfonsoeromero** [fergunet/tesis#11]
- "to attain significant performance in its EAs" -> no sería "their" (el sujeto es practitioners, plural)?
- "and changing these parameters in running time" -> si pegase ahí, ¿podría decirse "and changing them" para evitar repetir parameters tanto?
- "The parameter tuning consist in" -> "The parameter tuning consistS in"
- "and do not change these parameters during runtime" yo esto lo cambiaba por "and not changing these parameters during runtime", para concordar con "establishing".
- "according how are changes made:" -> "according to how the changes are made:"
- "divided the available devices in" -> "divided the available devices into"
- "Besides ordering the nodes" --> "Besides, ordering the nodes"

**Comment by fergunet** [comment]
Fixed! :)
