### ISSUE TITLE
Sacar al doctorando del ascensor 

### ISSUE THREAD

**Issue by deantares** [fergunet/tesis#13]
Es requerido sacar al futuro doctor del ascensor en el que se ha quedado atrapado

**Comment by deantares** [comment]
Conseguido!

**Comment by JJ** [comment]
¿Dónde se ha quedado encerrado la criatura?

2014-05-08 15:39 GMT+02:00 Antonio Fernández Ares notifications@github.com
:

> Conseguido!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fergunet/tesis/issues/13#issuecomment-42550498
> .

## 

JJ

**Comment by fergunet** [comment]
En el ascensor de mi casa. He hecho un storify y todo: https://storify.com/fergunet/fergu-encerrado-en-el-ascensor

Como ya he salido, cierro el issue.

**Comment by victoriano** [comment]
xD
