### ISSUE TITLE
Dejar los ficheros que sí correspondan a la tesis

### ISSUE THREAD

**Issue by JJ** [fergunet/tesis#2]
`./compilar` me da un montón de errores, ficheros .sty que no están principalmente. Comprobar cuales hacen falta realmente (si no, quitarlos del .tex) y añadirlos al repo, que no son estilos por defecto de LaTeX

**Comment by fergunet** [comment]
He actualizado el compilar, mira a ver si ahora te compila.

**Comment by JJ** [comment]
No, falta por lo menos mcaption.sty sidecap.sty multirow.sty lettrine.sty... y ahí he parado de compilar

**Comment by fergunet** [comment]
Eliminados ficheros rarunos y añadidos requisitos para compilar en el README
