### ISSUE TITLE
Numerar los ficheros de los capítulos para que sepa uno en qué orden van

### ISSUE THREAD

**Issue by JJ** [fergunet/tesis#3]
Ponerles 00-intro 01-procImagenes y así sucesivamente para que uno, sin necesidad de mirar el fichero `tesis.tex`, sepa en qué orden van (y hay que corregirlos). Puedes hacerlo con `git mv` sin perder la historia. Muevo uno de ellos, te toca a ti el resto.

**Comment by fergunet** [comment]
Hecho.
