### ISSUE TITLE
[Capitulo 02] Clasificación de los EAs

### ISSUE THREAD

**Issue by fergunet** [fergunet/tesis#6]
Definir una posible clasificación de los EAs para el Capítulo "Evolutionary Algorithms"

Actualmente:
- Clasificación de los EAs:
  GA, ES, GP, EP, Otros (DE, BOA), Meméticos
- Clasificación de los EAs paralelos
  1. Clasificación Tradicional
     Paralelismo Global
     Estructurados (grano fino, grano grueso)
  2. Aproximaciones no-convencionales
     - P2P
     - Pool
     - Grid y Volunteer

Cambiarlo a (posible):
- Clasificación de los EAs:
  1. Clasificación tradicional (propuesta por Eiben)
  2. Nuevos modelos (o aproximaciones?): BOA, DE, Meméticos...
- Clasificación de los EAs paralelos
  1. Clasificación Tradicional
     _Esta clasificación no tiene en cuenta los problemas tal y tal..._
     - Paralelismo Global
     - Estructurados (grano fino, grano grueso)
  2. Nuevos modelos _(quizás otro título?)_
     _Estos nuevos modelos incluyen cosas como la volatilidad, heterogeneidad... etc._
     - P2P
     - Pool
     - GRID

Vale, ahora que lo veo es prácticamente igual. Pensar una clasificación mejor.

**Comment by JJ** [comment]
Lo que tienes que pensar primero es _cómo_ lo vas a clasificar. Y luego
hacer la clasificación.

**Comment by fergunet** [comment]
Al final he pasado de tantas clasificaciones y movidas (clasificar por P2P o por cloud) y lo he dejado así:
1. Types of Evolutionary Algorithms
   - Classic classification of EAs
   - Other models
2. Parallel and Distributed Evolutionary Algorithms models
   - Traditional parallelization classification
   - New trends on parallel EAs
3. Parameter adaptation in Evolutionary Algorithms
   - Parameter Control and Parameter Tuning
   - Adaptation in heterogeneous hardware
4. Development of Evolutionary Algorithms
   - Design of EAs
   - Frameworks for EAs
5. Conclusions

¿Está así más claro?

Por supuesto enlazando cada cosa diciendo qué problemas tiene cada uno y enlazando con "en esta tesis se hará..."

**Comment by JJ** [comment]
Algo más, pero hay que ver realmente qué va en cada sitio...

2014/1/17 Pablo García Sánchez notifications@github.com

> Al final he pasado de tantas clasificaciones y movidas (clasificar por P2P
> o por cloud) y lo he dejado así:
> 
>    1.
> 
>    Types of Evolutionary Algorithms
>     - Classic classification of EAs
>       - Other models
>     2.
> 
>    Parallel and Distributed Evolutionary Algorithms models
>     - Traditional parallelization classification
>       - New trends on parallel EAs
>     3.
> 
>    Parameter adaptation in Evolutionary Algorithms
>     - Parameter Control and Parameter Tuning
>       - Adaptation in heterogeneous hardware
>     4.
> 
>    Development of Evolutionary Algorithms
>     - Design of EAs
>       - Frameworks for EAs
>     5.
> 
>    Conclusions
> 
> ¿Está así más claro?
> 
> Por supuesto enlazando cada cosa diciendo qué problemas tiene cada uno y
> enlazando con "en esta tesis se hará..."
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fergunet/tesis/issues/6#issuecomment-32627614
> .

## 

JJ
