### ISSUE TITLE
Random comments de 1.1

### ISSUE THREAD

**Issue by alfonsoeromero** [fergunet/tesis#8]
1) A veces se repiten algunas palabricas

Ejemplo, introducción del capítulo 1 (repeticiones en _..._):

Initially the EAs were proposed as a fixed set of steps with differ-
ent operators and data structures. Then, _different_ ways to parallelize
these algorithms were also _proposed_, with new classifications and op-
erations. Nowadays, new emerging trends that deal with new technolo-
gies (such as P2P or Cloud Computing) and new algorithmic methods
(such as parameter adaptation) are being used. These trends require
a new way to develop EAs taking into account some lacks, such as
integration of heterogeneous elements or dynamic resources.

_As can be seen_, these kind of algorithms _can be seen_ (además, el primero sería as it can be seen).

Algunas expresiones se repiten también un poquito. Te sugiero sinónimos:
take into account -> take into consideration
different -> several (cuando pueda sustituirse por la misma)
usually (3 veces en "genetic programming") -> commonly, frequently

2) (posibles) Errorcillos
- Hay un "neuronal networks" por ahí (neural?)
- "Combining elements of previous algorithms with other heuristics are
  the base of Memetic Algorithms (MAs)." -> yo creo que es "is" en vez de "are"
- "Other EAs, that does not match" -> "Other EAs that do not match" (coma y "do")
- El pobre "Smith" se ha quedado sin h en una de las citas (Smit)

**Comment by JJ** [comment]
Muchas gracias por los comentarios, Alfonso.

**Comment by fergunet** [comment]
Arreglados!
