### ISSUE TITLE
Cosicas bonicas de 1.2

### ISSUE THREAD

**Issue by alfonsoeromero** [fergunet/tesis#9]
- "or inside robots, who learn on-line from the environment" yo pondría "robots, learning from the environment in an online manner".
- "An example of EA that has been" --> "An example of one EA that has been"
- Ya por ser estilosos, ten cuidaico con "neighbour" y derivados. "neighbor" es americano, "neighbour" es inglés. Vecindario, por tanto es "neighborhood" (useño) o "neighbourhood" (inglés). En la figura 1.3 tienes el neighbourhood "inglés", pero en el punto 5.1 usas "neighborhood". La peña de los journals y tal también insisten mucho que se adopte o la convención inglesa, o la americana, pero no ambas. En general en la tesis se usa "optimization" y no "optimisation", así que yo cambiaría los neighbors a americano, a menos que you.supervisor() no esté de acuerdo. En cualquier caso sí que merece la pena unificar eso.

**Comment by fergunet** [comment]
Hecho!
